FROM node:18-alpine

RUN apk add --no-cache dumb-init

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodeuser -u 1001

WORKDIR /usr/src/app

RUN chown -R nodeuser:nodejs /usr/src/app
USER nodeuser

COPY --chown=nodeuser:nodejs package*.json ./

RUN npm ci && npm cache clean --force

EXPOSE 3000

ENTRYPOINT ["dumb-init", "--"]

CMD ["npm", "run", "dev"]