services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run dev
